const AIRTABLE_API_KEY='keyLAa76jzbPzUZBs';
const CUSTOMER_BASE_KEY='appzb4plafBCqDdvJ';
const CARRIER_BASE_KEY='appnZ4sj3I7uwCRAR';
const SUGGESTION_BASE_KEY='appXrQhBlxSbWJYQh'

export {AIRTABLE_API_KEY,CUSTOMER_BASE_KEY,CARRIER_BASE_KEY,SUGGESTION_BASE_KEY};